[package]
name = "befunge-interpreter"
version = "0.1.0"
authors = ["jpnykw <jpnykw@gmail.com>", "luckylat <lacklat.key@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

